# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grSimMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grSimMessage.proto',
  package='grSimMessage',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12grSimMessage.proto\x12\x0cgrSimMessage\"+\n\tgrSimInfo\x12\n\n\x02id\x18\x01 \x02(\r\x12\x12\n\nisInfrared\x18\x02 \x01(\x08'
)




_GRSIMINFO = _descriptor.Descriptor(
  name='grSimInfo',
  full_name='grSimMessage.grSimInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grSimMessage.grSimInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInfrared', full_name='grSimMessage.grSimInfo.isInfrared', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['grSimInfo'] = _GRSIMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

grSimInfo = _reflection.GeneratedProtocolMessageType('grSimInfo', (_message.Message,), {
  'DESCRIPTOR' : _GRSIMINFO,
  '__module__' : 'grSimMessage_pb2'
  # @@protoc_insertion_point(class_scope:grSimMessage.grSimInfo)
  })
_sym_db.RegisterMessage(grSimInfo)


# @@protoc_insertion_point(module_scope)
